---

- name: cikube | play | Provision a generic node image
  hosts: default
  become: yes
  any_errors_fatal: yes
  roles:
    - rcny.cikube.utils
    - rcny.cikube.nerdctl
    - rcny.cikube.experience
    - rcny.cikube.raid_localssd
    - rcny.cikube.cikube_tools
    - rcny.cikube.k3s_base
    - rcny.cikube.sysctl
    - rcny.cikube.finalize
