---
# tasks file for cikube_tools

- name: cikube | cikube_tools | Gather the facts if invoked partially
  ansible.builtin.setup:
  tags:
    - never
    - cikube-cikube-tools

- name: cikube | cikube_tools | Install scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  loop:
    - cikube-init
    - cikube-server-taint
    - cikube-storage-ln
  tags:
    - cikube-cikube-tools
