#!/bin/bash

set -eux

# check for --oidc-client-secret arg and get its value
CLIENT_SECRET=""
for i in "$@"; do
    case $i in
        --oidc-client-secret=*)
        CLIENT_SECRET="${i#*=}"
        shift
        ;;
        *)
        # unknown option
        ;;
    esac
done

if [ -z "$CLIENT_SECRET" ]; then
    echo "Error: --oidc-client-secret not provided"
    exit 1
fi

# install oidc-login via kubectl krew
kubectl krew install oidc-login

# template cikube-kubeconfig.yml
TEMP_FILE="temp-cikube-kubeconfig.yml"
sed "s/REPLACEME_CLIENT_SECRET/$CLIENT_SECRET/g" cikube-kubeconfig.yml > $TEMP_FILE

# merge kubeconfigs
MERGED_KUBECONFIG="merged-kubeconfig.yaml"
KUBECONFIG=$HOME/.kube/config:$TEMP_FILE kubectl config view --flatten > $MERGED_KUBECONFIG
cp $MERGED_KUBECONFIG $HOME/.kube/config

# clean up
rm $TEMP_FILE
rm $MERGED_KUBECONFIG

echo "Success: Merged cikube-kubeconfig.yml into your kubeconfig"
