---
# tasks file for sysctl

- name: cikube | sysctl | Gather the facts if invoked partially
  ansible.builtin.setup:
  tags:
    - never
    - cikube-sysctl

- name: cikube | sysctl | Ensure Ansible sysctl file exists
  ansible.builtin.file:
    path: /etc/sysctl.d/90-cikube.conf
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: 0644
  tags:
    - cikube-sysctl

- name: cikube | sysctl | Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/90-cikube.conf
    reload: true
  tags:
    - cikube-sysctl

- name: cikube | sysctl | Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/90-cikube.conf
    reload: true
  tags:
    - cikube-sysctl

- name: cikube | sysctl | Enable IPv6 router advertisements
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "2"
    state: present
    sysctl_file: /etc/sysctl.d/90-cikube.conf
    reload: true
  tags:
    - cikube-sysctl

# Required for upstream Debian kernels
# If we start to compile the kernel ourselves with vanilla options, we can remove this
- name: cikube | sysctl | Enable user namespaces for non-root users
  ansible.posix.sysctl:
    name: kernel.unprivileged_userns_clone
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/90-cikube.conf
    reload: true
  tags:
    - cikube-sysctl
